VEGA-753: Отображать подтверждение об отмене создания проекта при нажатии кнопки Выйти
gpn-prototypes/vega-shell pull request #108
Opened 2021-02-15 10:30 UTC by hitmanet

Jira issue: VEGA-753

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] Документация: отражены все изменения в API конфигов и описаны важные особенности реализации или использования
- [ ] Конфигурационные файлы: новые файлы или изменения текущих были проверены в тестовых репозиториях

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

2021-02-15 10:38 UTC, hitmanet commented
Мержить одновременно с https://github.com/gpn-prototypes/vega-sp/pull/160

2021-02-15 13:13 UTC, Inzephirum requested changes

2021-02-15 13:13 UTC, Inzephirum commented on src/components/Header/Header.tsx
> +  };
думаю, что пока самым простым решением будет создать для `logout` отдельный роут в обвязке, который будет вызывать `identity.logout` и рендерить `loader`. При разлогине должно редиректнуть на `/login`. Только нужно будет проверить, что`redirectTo !== "/logout"`.
Тут кнопку "Выйти" нужно будет заменить на `<Link to="/logout" />`.

2021-02-15 15:45 UTC, hitmanet commented
@Inzephirum поправил

2021-02-16 04:59 UTC, Inzephirum commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +      )}
Почему просто так не сделать?
```suggestion
      <Route path="/logout">
        <LogoutView redirectPathname={previousPathname} />
      </Route>
```

2021-02-16 04:59 UTC, Inzephirum commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +        </Route>
а, хм, а разве этого не достаточно?

2021-02-16 04:59 UTC, Inzephirum commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  return <Redirect to={`/login?${getQuery()}`} />;
У нас же и так редирект должен быть, если мы не авторизованы. Я думал здесь просто Loader рисовать.

2021-02-16 04:59 UTC, Inzephirum commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  };
Путь редиректа уже вычисляется в ApplicationRoutes. Может просто туда проверку добавить, что если `redirectTo=/logout`, то redirectTo вообще удаляем

2021-02-16 14:30 UTC, hitmanet commented on src/components/Header/Header.tsx
> +  };
исправил

2021-02-16 14:30 UTC, hitmanet commented
@Inzephirum исправил

2021-02-17 07:14 UTC, sergavshin commented on src/app/shell.ts
> +    console.log('here');
console.log

2021-02-17 07:14 UTC, sergavshin commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  return useCallback(() => set((s) => !s), [set]);
еще можно через `useReducer`, тогда `useCallback` не нужен
```suggestion
  const [, forceUpdate] = useReducer((s) => s + 1, 0);
  return forceUpdate;
```

2021-02-17 07:14 UTC, sergavshin commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +    const lastAuthMessage = bus.peek({ channel: 'auth', topic: 'login' });
хм, сейчас понял, что надо сохранять значение до `useMount`, а в `useMount` доставать еще раз, и сравнивать, что значение не изменилось. Иначе всегда будет лишний ререндер.

2021-02-17 07:14 UTC, sergavshin commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +          lastAuthorizedRoute.current = previousPathname;
а мы не должны это во время рендера `ApplicationRoutes` проверять? Типо если мы авторизованы, и если путь не `/login` или `/logout`, то обновлять `lastAuthorizedRoute`

2021-02-17 07:53 UTC, maksim-kononov-csssr approved these changes

2021-02-17 08:07 UTC, hitmanet commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +          lastAuthorizedRoute.current = previousPathname;
исправил

2021-02-17 08:07 UTC, hitmanet commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +    const lastAuthMessage = bus.peek({ channel: 'auth', topic: 'login' });
исправил

2021-02-17 08:07 UTC, hitmanet commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  return useCallback(() => set((s) => !s), [set]);
исправил

2021-02-17 08:08 UTC, hitmanet commented on src/app/shell.ts
> +    console.log('here');
убрал

2021-02-17 09:06 UTC, sergavshin approved these changes

2021-02-17 15:19 UTC, merged