VEGA-915: Написать скрипты для сборки фронтенда в КСПД
gpn-prototypes/vega-shell pull request #112
Opened 2021-02-16 12:33 UTC by maksim-kononov-csssr

Jira issue: VEGA-915

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] Документация: отражены все изменения в API конфигов и описаны важные особенности реализации или использования
- [ ] Конфигурационные файлы: новые файлы или изменения текущих были проверены в тестовых репозиториях

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

2021-02-16 12:35 UTC, hitmanet approved these changes

2021-02-16 12:56 UTC, alexeyandriyash commented on graphql.schema.json
> +            "name": "status",
Looks like junk code? Is't it?

2021-02-16 12:59 UTC, alexeyandriyash commented on ci/build-entrypoint.sh
> +if [ -z "$NPM_URI" ] || [ -z "$NPM_AUTH_TOKEN" ]
Could you please add set-dev-npm-config.sh and add setup inside default(current) development NPM_* variable value

2021-02-16 13:00 UTC, alexeyandriyash commented on ci/build.sh
> +VERSION="${BUILD_VERSION:=1}"
FR_BUILDER_VERSION="1"

2021-02-16 13:06 UTC, ijon requested changes
Invalid issue number referenced, both in commit messages and in pr title and description.
Generally core team can't accept anything other than from the central project tracker.
And this pr closely tied to the work of the core team.

Please change issue references to the ones core team could see and work on.

2021-02-16 13:45 UTC, maksim-kononov-csssr commented on graphql.schema.json
> +            "name": "status",
Относительно схемы что сейчас в мастер ветке, схема на сервере изменилась и скрипты автоматически ее обновили. В теории можно было бы убрать эти файлы из коммита, но у нас как правило нет отдельной задачи обновить схему, поэтому обновляем по необходимости

2021-02-16 13:47 UTC, maksim-kononov-csssr commented on ci/build.sh
> +VERSION="${BUILD_VERSION:=1}"
Ты имеешь ввиду заменить название переменной `VERSION` на `FR_BUILDER_VERSION`?

2021-02-16 13:47 UTC, maksim-kononov-csssr commented
> Invalid issue number referenced, both in commit messages and in pr title and description.
> Generally core team can't accept anything other than from the central project tracker.
> And this pr closely tied to the work of the core team.
> 
> Please change issue references to the ones core team could see and work on.

Исправил.

2021-02-16 15:53 UTC, maksim-kononov-csssr commented on ci/build.sh
> +VERSION="${BUILD_VERSION:=1}"
Исправил

2021-02-18 09:10 UTC, maksim-kononov-csssr commented on ci/Dockerfile
> +
Исправил

2021-02-18 09:10 UTC, maksim-kononov-csssr commented on ci/build.sh
> +  docker build -t vega/frontend-builder:$FE_BUILDER_VERSION ./ci
Добавил общую переменную: TAG="$VEGA_REPOPREFIX/$IMAGE_NAME:$FE_BUILDER_VERSION"

2021-02-18 09:11 UTC, maksim-kononov-csssr commented on ci/build.sh
> +
Добавил для IMAGE_NAME значение по умолчанию

2021-02-18 09:11 UTC, maksim-kononov-csssr commented on ci/build.sh
> +  vega/frontend-builder:$VERSION \
Добавил общую переменную: TAG="$VEGA_REPOPREFIX/$IMAGE_NAME:$FE_BUILDER_VERSION"

2021-02-18 12:47 UTC, alexeyandriyash approved these changes

2021-02-18 13:10 UTC, merged