VEGA-905: Добавить в игнор кодогенерацию в vega-shell
gpn-prototypes/vega-shell pull request #144
Opened 2021-03-09 11:16 UTC by hitmanet

Jira issue: VEGA-905

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] Документация: отражены все изменения в API конфигов и описаны важные особенности реализации или использования
- [ ] Конфигурационные файлы: новые файлы или изменения текущих были проверены в тестовых репозиториях

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

2021-03-10 07:37 UTC, sergavshin approved these changes

2021-03-10 13:33 UTC, fixmylie approved these changes

2021-03-11 07:18 UTC, maksim-kononov-csssr requested changes

2021-03-11 07:18 UTC, maksim-kononov-csssr commented on .gitignore
> +
Я уже добавил это правило: https://github.com/gpn-prototypes/vega-shell/blob/9a5d10e551ba1c157293daf2c1abbcec3b79696b/.gitignore#L18

2021-03-11 07:18 UTC, maksim-kononov-csssr commented on .github/workflows/build-static.yaml
> +
Я уже добавил эту команду: https://github.com/gpn-prototypes/vega-shell/blob/9a5d10e551ba1c157293daf2c1abbcec3b79696b/.github/workflows/build-static.yaml#L35

2021-03-11 07:18 UTC, maksim-kononov-csssr commented on ci/build-entrypoint.sh
> +yarn generate:types
А вот это забыл добавить, а стоило бы

2021-03-11 08:49 UTC, maksim-kononov-csssr approved these changes

2021-03-15 07:24 UTC, sergavshin commented
@hitmanet можешь глянуть почему ci падает?

2021-03-15 07:27 UTC, hitmanet commented
> @hitmanet можешь глянуть почему ci падает?

подребейзить надо будет

2021-03-15 07:52 UTC, merged