[VEGA-3402] feat(global): Добавление детального слияния версий
gpn-prototypes/vega-shell pull request #182
Opened 2021-04-14 10:41 UTC by lipgen

Jira issue: VEGA-3402

## Описание изменений
Добавлено детальное слияние версий

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] Документация: отражены все изменения в API конфигов и описаны важные особенности реализации или использования
- [ ] Конфигурационные файлы: новые файлы или изменения текущих были проверены в тестовых репозиториях

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

2021-04-14 12:41 UTC, lipgen commented on src/services/graphql-client/project-diff-resolver/project-diff-resolver.ts
> +      const diff = this.diffPatcher.diff(remote, local);
Подебажил, local и localChanges приходят одинаковыми (как минимум в рб), поэтому вся проверка пропускается. Думаю здесь должно быть сравнение версии сервера и локальной.

2021-04-14 12:45 UTC, lipgen commented on src/services/graphql-client/project-diff-resolver/project-diff-resolver.ts
> +        if (this.mergeStrategy.resolvers.length) {
Здесь алгоритм работы следующий, патчим версию сервера по дефолту с помощью jsondiffpatch, а затем прорабатываем переданные резолверы. Если матчер указывает на массив, то применяем резолвер к каждому его элементу, а иначе применяем резолвер к самому элементу.

2021-04-15 06:21 UTC, Davs777 requested changes

2021-05-13 09:01 UTC, Davs777 approved these changes

2021-06-11 08:26 UTC, alekskond approved these changes

2021-06-11 08:28 UTC, merged