VEGA-672: Заменить роутер в vega-shell
gpn-prototypes/vega-shell pull request #49
Opened 2020-11-27 08:31 UTC by hitmanet

Jira issue: VEGA-672

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] Документация: отражены все изменения в API конфигов и описаны важные особенности реализации или использования
- [ ] Конфигурационные файлы: новые файлы или изменения текущих были проверены в тестовых репозиториях

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

2020-11-27 09:08 UTC, c1n1k commented on src/application-parcel.tsx
> +    bus.send({ topic: 'server-error', channel: 'error', payload: null, self: true });
для чего надо всегда слать ошибку?

2020-11-27 09:18 UTC, c1n1k approved these changes

2020-11-27 09:40 UTC, fixmylie commented on src/application-parcel.tsx
> +    bus.send({ topic: 'server-error', channel: 'error', payload: null, self: true });
и payload null :thinking:

2020-11-27 09:40 UTC, fixmylie commented on src/application-parcel.tsx
> +                <NotFoundView />
почему нужно столько нотфаундов в роутере?

2020-11-27 09:41 UTC, fixmylie commented
Упал билд

2020-11-27 09:44 UTC, hitmanet commented on src/application-parcel.tsx
> +    bus.send({ topic: 'server-error', channel: 'error', payload: null, self: true });
Убираю это, пока вип

2020-11-27 09:44 UTC, hitmanet commented on src/application-parcel.tsx
> +                <NotFoundView />
На каждый уровень вложенности нужно добавлять

2020-11-27 09:46 UTC, hitmanet commented on src/application-parcel.tsx
> +                <NotFoundView />
Если добавить на самый верхний уровень, то некорректные роуты, допустим, на том же слое работы с проекта обрабатываться не будут

2020-11-27 13:51 UTC, hitmanet commented
@fixmylie все поправил

2020-11-27 16:05 UTC, c1n1k approved these changes

2020-11-30 07:53 UTC, fixmylie approved these changes

2020-11-30 13:28 UTC, Inzephirum requested changes

2020-11-30 13:28 UTC, Inzephirum commented on src/components/AuthGuard/AuthGuard.tsx
> +};
```suggestion
type AuthGuardProps = {
  isLoggedIn: boolean;
  authPath: string;
};

export const AuthGuard: React.FC<AuthGuardProps> = (props) => {
  const { authPath, isLoggedIn } = props;

  const location = useLocation();

  if (!isAuthPage && !isLoggedIn) {
    return <Redirect to={authPath} />;
  }

  if (isLoggedIn) {
    return props.children;
  }

  return null;
};
```
плюс не нужно выносить в `utils/contants` пути `AUTH_PAGE` и `MAIN_PAGE`, `MAIN_PAGE` не нужен, а `AUTH_PAGE` можно будет передать в тестах через props;

или можно вообще без `AuthGuard`

```tsx

const App = () => {
  const [isLoggedIn, setIsLoggedIn] = React.useState(identity.isLoggedIn);

  React.useEffect(() => {
    bus.subscribe // подписаться на события авторизации, и выставлять isLoggedIn 
  })

  return (
    <Router>
      <Switch>
        <Route path="/login">
          <Parcel config={loadConfig('@vega/auth')} />
        </Route>
        {!isLoggedIn && <Redirect to="/login" />}
        <Redirect from="/" to="/projects">  
        <Route path="/projects">
          <header>...</header>
          <main>...</main>
        </Route>
        <NotFound />
      </Switch>
    </Router>
  )
}
```

2020-11-30 14:44 UTC, hitmanet commented on single-spa-react.d.ts
> +    // define here what props you need
уберу

2020-11-30 14:44 UTC, hitmanet commented on src/application-parcel.tsx
> +            </div>
та же проблема, что и с рб. Без свитча все было ок, с ним нет. Поставлю задачу чтобы разобраться

2020-12-01 08:48 UTC, hitmanet commented on src/application-parcel.tsx
> +                    <Parcel config={loadConfig('@vega/rb')} {...applicationProps} />
Я лучше сделаю обычным контекстом, потому что не оч понятно как работает SingleSpaContext. Доки по нему тоже нет, а по коду в src есть ощущение что он создается компонентом Parcel (или если юзать singleSpaReact функцию)

2020-12-03 10:56 UTC, c1n1k approved these changes

2020-12-07 13:47 UTC, Inzephirum commented on src/components/Application/Application.tsx
> +  const loadConfig = (url: string): (() => Promise<System.Module>) => () => System.import(url);
```suggestion
  const config = React.useMemo(() => System.import(url), [url]);
```

2020-12-07 13:47 UTC, Inzephirum commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  });
почему при смене страницы нужно очищать состояние?

2020-12-07 13:48 UTC, hitmanet commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  });
чтобы 500 ошибка не оставалась на странице

2020-12-07 13:48 UTC, hitmanet commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  });
был ты на сп, перешел на рб, на рб 500, ты через стрелочку в браузере вернулся на сп

2020-12-07 13:48 UTC, hitmanet commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  });
если не очищать то будет 500

2020-12-07 13:50 UTC, Inzephirum commented on .eslintrc.js
> +    'react/no-unused-prop-types': 'off',
это правило точно нужно отключать?

2020-12-07 14:01 UTC, Inzephirum commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  });
Я просто думаю стоит ли это хранить в состоянии реакта. Может это лучше в состояние `location` записывать?

2020-12-07 14:02 UTC, Inzephirum commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  });
в целом так тоже пойдет

2020-12-07 14:15 UTC, hitmanet commented on src/components/ApplicationRoutes/ApplicationRoutes.tsx
> +  });
мне кажется, так более явно

2020-12-07 14:34 UTC, hitmanet commented
@Inzephirum все поправил

2020-12-08 07:19 UTC, Inzephirum commented on src/App.css
> +}
Зря в этой задаче стили шапки правил. Может быть ненужный регресс или конфликты с другими задачами. Лучше в отдельную задачу такое выносить.

2020-12-08 07:20 UTC, Inzephirum approved these changes

2020-12-08 07:20 UTC, hitmanet commented on src/App.css
> +}
Я созвонился с Олей, она заапрувила это

2020-12-08 07:27 UTC, Inzephirum commented
ждёт мержа https://github.com/gpn-prototypes/vega-shell/pull/39

2020-12-08 07:45 UTC, merged