VEGA-678: Подключить vega-sdk и заменить все импорты в сервисы
gpn-prototypes/vega-shell pull request #51
Opened 2020-11-30 09:06 UTC by hitmanet

Jira issue: VEGA-678

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] Документация: отражены все изменения в API конфигов и описаны важные особенности реализации или использования
- [ ] Конфигурационные файлы: новые файлы или изменения текущих были проверены в тестовых репозиториях

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

2020-11-30 13:42 UTC, Inzephirum commented
@hitmanet давай в `vega-sdk` тоже через PRs изменения вносить. А то там с выносом в отдельный модуль появился спорный код, который уже в мастере.

2020-11-30 13:48 UTC, Inzephirum commented on src/components/Error/ErrorView.tsx
> +import { ShellServerError } from '@gpn-prototypes/vega-sdk';
а должна ли sdk знать, что у нас есть обвязка? не очень понятна связка `Shell` и `ServerError`

2020-11-30 14:18 UTC, hitmanet commented
> @hitmanet давай в `vega-sdk` тоже через PRs изменения вносить. А то там с выносом в отдельный модуль появился спорный код, который уже в мастере.

Я больше так не буду

2020-11-30 14:40 UTC, hitmanet commented on src/components/Error/ErrorView.tsx
> +import { ShellServerError } from '@gpn-prototypes/vega-sdk';
Заменю название типа в sdk

2020-12-03 10:13 UTC, c1n1k commented
@hitmanet конфликты

2020-12-07 11:32 UTC, c1n1k commented on package.json
>      "@gpn-prototypes/vega-ui": "^2.15.1",
2.15.7 актуальная версия

2020-12-07 11:33 UTC, c1n1k requested changes
надо изменить версию vega-ui

2020-12-09 13:30 UTC, c1n1k approved these changes

2020-12-10 06:38 UTC, c1n1k approved these changes

2021-02-17 07:37 UTC, closed without merging