VEGA-576: Доработки для авторизации и аутентификации
gpn-prototypes/vega-shell pull request #59
Opened 2020-12-07 15:06 UTC by maksim-kononov-csssr

Jira issue: VEGA-576

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] Документация: отражены все изменения в API конфигов и описаны важные особенности реализации или использования
- [ ] Конфигурационные файлы: новые файлы или изменения текущих были проверены в тестовых репозиториях

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

2020-12-07 15:21 UTC, hitmanet commented on src/utils/api-client/api-client.ts
> +    try {
Может весь этот блок вынести отдельно? А то повторяется

2020-12-07 15:56 UTC, maksim-kononov-csssr commented on src/utils/api-client/api-client.ts
> +    try {
Можно вынести в функцию создания ошибки

2020-12-07 16:12 UTC, c1n1k commented on src/utils/identity/identity.ts
> +      Если accessToken был удален из ls (accessToken === null), то все равно лучше перелогиниться
почему?

2020-12-07 16:16 UTC, c1n1k commented on src/utils/identity/identity.ts
> +  public logout = (shouldDestroyTokens = true): void => {
для чего это условие?

2020-12-08 06:08 UTC, fixmylie requested changes

2020-12-08 06:08 UTC, fixmylie commented on src/vega-shell.ts
> +    identity.logout(false);
а тут случаем не сломалась логика авторизации?
Здесь отправлялось событие, а `{ channel: 'auth', topic: 'logged-out' }` слушал и делал редиректы.

2020-12-08 06:32 UTC, c1n1k commented on src/utils/identity/identity.ts
> +  private refreshPromise: ReturnType<APIClient['refresh']> | null;
тут разве тип не известен? AuthRefreshResponse?

2020-12-08 06:47 UTC, c1n1k commented on src/utils/identity/identity.ts
> +    return null;
нужна какая-то более внятная обработка, потому что в apollo клиент ты отдаешь null, хотя разумнее инициировать переход пользователя на авторизацию с уведомлением об ошибке

2020-12-08 06:49 UTC, c1n1k commented on src/utils/graphql-client/graphql-client.ts
> +    const token = await identity.getToken();
нужно обработать `null`

2020-12-08 08:46 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +      Если accessToken был удален из ls (accessToken === null), то все равно лучше перелогиниться
Потому что нет сценария при котором система удалит один accessToken и оставит refreshToken. Если произошел такой сценарий - это либо токен был удален вручную, либо произошла какая-то ошибка - так что лучше полностью перелогиниться

2020-12-08 08:52 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +  public logout = (shouldDestroyTokens = true): void => {
Флаг shouldDestroyTokens управляет методом destroyTokens - для уничтожения токенов через сервер `auth/jwt/destroy`. По умолчанию уничтожать токены нужно, но могут быть сценарии когда этого не нужно делать. Например, когда у нас уже токены не валидны. Если отправить запрос на уничтожения невалидного токена (а запрос сам должен быть подписан с accessToken) сервер ответит ошибкой 401

2020-12-08 08:53 UTC, maksim-kononov-csssr commented on src/utils/identity/tokenHandlers.ts
> +function decodeToken(token: string): DecodedToken | null {
Сделаю

2020-12-08 08:56 UTC, maksim-kononov-csssr commented on src/vega-shell.ts
> +    identity.logout(false);
Отправка сообщения `sendMessageOnLogout` напрямую в обход identity только запутывает логику. Метод identity.logout при выполнении кроме своей внутренней логики вызовет sendMessageOnLogout (https://github.com/gpn-prototypes/vega-shell/blob/909996af9a156d9cdcece0ca2538a15a3e3e073b/src/vega-shell.ts#L44)

2020-12-08 08:58 UTC, maksim-kononov-csssr commented on src/vega-shell.ts
> +    identity.logout(false);
По хорошему, Identity должен быть единственным источником значения по авторизации. И логаут должен проходить через него. В противном случае одна часть приложения думает что мы разлогинились, а вторая что мы еще залогинены

2020-12-08 09:02 UTC, maksim-kononov-csssr commented on src/vega-shell.ts
> +    identity.logout(false);
Например, в identity.logout  отчищается LS и мы всегда уверены что при разлогине у нас чистый LS
А в случае sendMessageOnLogout(); - нужно ниже добавить еще одну строчку identity.removeTokens. Я так и сделал, но потом переделал на identity.logout(false);

2020-12-08 09:22 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +  private refreshPromise: ReturnType<APIClient['refresh']> | null;
Тут должен сохранится промис, что возвращается методом apiClient.refresh. Это сделано для того, чтобы в случае когда несколько запросов одновременно пытаются вызвать identity.refresh - первый его вызвал по настоящему, а остальные дожидались выполнения уже существующего промиса

2020-12-08 09:48 UTC, c1n1k commented on src/utils/identity/identity.ts
> +  public logout = (shouldDestroyTokens = true): void => {
а если на момент получения сервером токенов на дестрой они стали не валиными? отправил ты ещё валидными а пришли уже с истёкшим временем жизни? задавал такой вопрос бэку?

2020-12-08 09:54 UTC, c1n1k commented on src/utils/identity/identity.ts
> +      Если accessToken был удален из ls (accessToken === null), то все равно лучше перелогиниться
не лучше ли перезапросить новую пару токенов через рефреш? не будет лишних переходов

2020-12-08 09:57 UTC, c1n1k commented on src/utils/identity/identity.ts
> +  public logout = (shouldDestroyTokens = true): void => {
и сделай это условие более очевидным, объектом с семантичным свойством, иначе где-то в другом приложении не поймёшь о чем и для чего это даже с типами

2020-12-08 10:51 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +    return null;
если в apollo передать null, то он не поставит соответствующий заголовок в запрос, сервер на этот запрос вернет ошибку 401, она поймается уже существующим механизмом обработки 401-х ошибок и произойдет разлогин, пользователя выбросить на страницу авторизации

2020-12-08 10:52 UTC, maksim-kononov-csssr commented on src/utils/graphql-client/graphql-client.ts
> +    const token = await identity.getToken();
ответил в комментарии чуть выше

2020-12-08 10:53 UTC, c1n1k commented on src/utils/identity/identity.ts
> +    return null;
а зачем в таком случае лишний запрос?

2020-12-08 10:56 UTC, maksim-kononov-csssr commented on src/utils/api-client/api-client.ts
> +  public auth = async ({ login, password }: UserDataType): Promise<AuthObtainResponse> => {
на сколько я понимаю, достаточно указать тип возращаемого значения при успешном исходе

2020-12-08 10:58 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +    return null;
Справедливо. Присмотрюсь к этому механизму как его лучше сделать

2020-12-08 12:52 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +  public logout = (shouldDestroyTokens = true): void => {
объектом с семантичным свойством - что ты имеешь ввиду? Можешь пример привести?

2020-12-08 12:53 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +  public logout = (shouldDestroyTokens = true): void => {
> а если на момент получения сервером токенов на дестрой они стали не валиными? отправил ты ещё валидными а пришли уже с истёкшим временем жизни? задавал такой вопрос бэку?

Сервер вернет ошибку 401, мы ее получим и проигнорируем

2020-12-08 13:03 UTC, c1n1k commented on src/utils/identity/identity.ts
> +  public logout = (shouldDestroyTokens = true): void => {
`{needDestroy: true}`

2020-12-08 15:07 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +      Если accessToken был удален из ls (accessToken === null), то все равно лучше перелогиниться
Я считаю что лучше лишний переход в какой-то крайней ситуации, так более предсказуемо

2020-12-08 15:09 UTC, c1n1k commented on src/utils/identity/identity.ts
> +      Если accessToken был удален из ls (accessToken === null), то все равно лучше перелогиниться
для кого?

2020-12-08 15:35 UTC, maksim-kononov-csssr commented on src/utils/api-client/api-client.ts
> +    try {
Вынес в отдельную функцию создания ошибки

2020-12-08 15:37 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +      Если accessToken был удален из ls (accessToken === null), то все равно лучше перелогиниться
Для меня

2020-12-08 15:48 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +      Если accessToken был удален из ls (accessToken === null), то все равно лучше перелогиниться
Решили оставить так как есть до комментария Сергея

2020-12-08 16:18 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +  public logout = (shouldDestroyTokens = true): void => {
Сделал

2020-12-08 16:20 UTC, maksim-kononov-csssr commented on src/utils/identity/tokenHandlers.ts
> +function decodeToken(token: string): DecodedToken | null {
Я добавил todo в общий файл тестов для identity

2020-12-08 16:27 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +    return null;
Решили оставить так как есть до комментария Сергея

2020-12-09 09:20 UTC, Inzephirum commented on src/utils/identity/identity.ts
> +    return null;
Можно либо в случае `null` сделать `logout()` внутри метода, но только его нужно будет переименовать во что-то более понятное. Назвать как-нибудь `tryGetToken | verifyAndGetToken | tryGetTokenOrLogout`, в общем как-то, чтобы было понятно что возвращается промис + что может быть дополнительное действие в случае неудачи.
Либо можно проверять на `null` в линке, и сделать logout там, а сам запрос дальше не пускать

2020-12-09 09:22 UTC, maksim-kononov-csssr commented on src/vega-shell.ts
> +      identity.removeUserName();
объединить в один метод - да, хорошая идея
по поводу isLoggedIn - я думал в том ключе, чтобы делать reset в isLoggedIn если у нас не найдены ключи, но это кажется запутанным, ведь мы не знаем заранее в каком контексте мы вызовем isLoggedIn в будущем, нужно ли будет делать reset в том контексте/сценарии

2020-12-09 09:25 UTC, hitmanet commented on src/utils/api-client/api-client.ts
> +  public auth = async ({ login, password }: UserDataType): Promise<AuthObtainResponse> => {
Я бы все-таки указал все возможные типы, даже если тс не ругается

2020-12-09 09:30 UTC, Inzephirum commented on src/vega-shell.ts
> +      identity.removeUserName();
Наличие токенов у нас известно при инициализации сервиса. Мы их можем сразу вытащить из LS и держать внутри сервиса.

2020-12-09 11:12 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +  public destroyTokens = async (): Promise<string> => {
Исправил

2020-12-09 11:14 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +    localStorage.removeItem(LS_USER_LAST_NAME_KEY);
Исправил

2020-12-09 11:19 UTC, maksim-kononov-csssr commented on src/vega-shell.ts
> +      identity.removeUserName();
Объединил removeTokens и removeUserName в один метод.
Доработку по работе с токенами вынесу в задачу по рефакторингу.

2020-12-09 11:22 UTC, maksim-kononov-csssr commented on src/utils/identity/identity.ts
> +    return null;
Обсудили этот момент, нужно будет доработать, вынесу в задачу по рефакторингу

2020-12-09 13:52 UTC, c1n1k approved these changes

2020-12-09 13:52 UTC, hitmanet approved these changes

2020-12-16 10:28 UTC, maksim-kononov-csssr commented
Функционал был добавлен через ветку VEGA-576-2 в мастер

2020-12-16 10:28 UTC, closed without merging