VEGA-802: Написать тесты для утилит из tokenHandlers.ts
gpn-prototypes/vega-shell pull request #80
Opened 2021-01-11 07:28 UTC by maksim-kononov-csssr

Jira issue: VEGA-802

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] Документация: отражены все изменения в API конфигов и описаны важные особенности реализации или использования
- [ ] Конфигурационные файлы: новые файлы или изменения текущих были проверены в тестовых репозиториях

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

2021-01-11 09:27 UTC, hitmanet approved these changes

2021-01-11 12:05 UTC, c1n1k approved these changes

2021-01-12 04:11 UTC, fixmylie requested changes

2021-01-12 04:11 UTC, fixmylie commented on yarn.lock
> +"@gpn-prototypes/vega-canvas@^0.1.11":
это скорее всего лишнее

2021-01-12 09:15 UTC, maksim-kononov-csssr commented on yarn.lock
> +"@gpn-prototypes/vega-canvas@^0.1.11":
Если переключиться на релиз ветку и сделать yarn, то он вот так обновится. Проверил сейчас еще раз

2021-01-12 13:38 UTC, fixmylie approved these changes

2021-01-12 13:38 UTC, fixmylie commented
@maksim-kononov-csssr можешь мержить, если нужно

2021-01-13 08:04 UTC, merged